# Generated by Django 3.2.16 on 2023-02-16 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emaillist2', '0002_alter_emaillist2user_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist2user',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
