# Generated by Django 3.2.16 on 2023-02-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist2', '0003_alter_emaillist2user_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist2user',
            old_name='author',
            new_name='user',
        ),
    ]
