# Generated by Django 3.2.16 on 2023-02-21 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Folder2',
        ),
    ]
