# Generated by Django 3.2.16 on 2023-01-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='author',
            field=models.CharField(max_length=100, verbose_name='발신인'),
        ),
    ]
