# Generated by Django 3.2.16 on 2023-01-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_filter_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='author',
            new_name='authorr',
        ),
    ]
